
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language, Theme } from './types';

// --- I18n System ---

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'Qingyun Cloud',
    'nav.dashboard': 'Ops Dashboard',
    'nav.tenants': 'Tenant Mgmt',
    'nav.resources': 'Resource Monitor',
    'nav.billing': 'Billing Center',
    'nav.alerts': 'Alert Center',
    'nav.algorithms': 'Algorithm Center',
    'nav.products': 'Product Center',
    'header.search': 'Search resources...',
    'header.role': 'Super Admin',
    'dashboard.activeTenants': 'Total Active Tenants',
    'dashboard.newThisWeek': '+2 new this week',
    'dashboard.criticalAlerts': 'Critical Alerts',
    'dashboard.immediateAttention': 'Requires immediate attention',
    'dashboard.monthlyRevenue': 'Monthly Revenue Est.',
    'dashboard.basedOnUsage': 'Based on current usage',
    'dashboard.systemHealth': 'System Health',
    'dashboard.apiLatency': 'API Latency: 45ms',
    'dashboard.globalApi': 'Global API Traffic (24h)',
    'dashboard.liveData': 'Live Data',
    'dashboard.storageDist': 'Storage Distribution',
    'dashboard.totalUsed': 'Total Used',
    'dashboard.alertsTitle': 'Critical Alerts & Warnings',
    'table.severity': 'Severity',
    'table.message': 'Message',
    'table.tenant': 'Tenant',
    'table.time': 'Time',
    'table.action': 'Action',
    'action.investigate': 'Investigate',
    'tenant.title': 'Tenant Management',
    'tenant.subtitle': 'Manage service lifecycle and access controls',
    'tenant.filter': 'Filter',
    'tenant.new': '+ New Tenant',
    'tenant.search': 'Search by name, ID or admin...',
    'tenant.showing': 'Showing',
    'tenant.col.name': 'Tenant Name / ID',
    'tenant.col.status': 'Status',
    'tenant.col.period': 'Service Period',
    'tenant.col.usage': 'Resource Usage',
    'tenant.col.balance': 'Balance',
    'tenant.col.actions': 'Actions',
    'tenant.loadMore': 'Load More Tenants',
    'billing.title': 'Billing Center',
    'billing.subtitle': 'Automated invoice generation and payment tracking',
    'billing.paymentSettings': 'Payment Settings',
    'billing.runCycle': 'Run Billing Cycle',
    'billing.totalRevenue': 'Total Revenue (This Month)',
    'billing.vsLast': '+12% vs last month',
    'billing.pendingInvoices': 'Pending Invoices',
    'billing.needsAttention': 'Needs attention',
    'billing.overdue': 'Overdue Amount',
    'billing.frozen': '3 accounts frozen',
    'billing.recent': 'Recent Invoices',
    'billing.col.id': 'Invoice ID',
    'billing.col.cycle': 'Billing Cycle',
    'billing.col.amount': 'Amount',
    'billing.col.status': 'Status',
    'billing.col.date': 'Date',
    'resource.title': 'Resource Monitor',
    'resource.subtitle': 'Real-time usage statistics and quota management',
    'resource.cloudStorage': 'Cloud Storage',
    'resource.sms': 'SMS Sent',
    'resource.apiCalls': 'API Calls',
    'resource.algoTasks': 'Algorithm Tasks',
    'resource.totalUsage': 'Total Usage',
    'resource.capacity': 'capacity',
    'resource.topConsumers': 'Top Resource Consumers',
    'resource.channelConfig': 'Channel Configuration',
    'resource.manageAll': 'Manage All',
    'resource.active': 'Active',
    'ai.title': 'AI Assistant',
    'ai.placeholder': 'Ask about tenants, alerts, or billing...',
    'ai.thinking': 'Thinking...',
    'ai.welcome': 'Hi! I am your Ops Assistant. How can I help you manage the platform today?',
    'algo.title': 'Algorithm Center',
    'algo.subtitle': 'Upload, audit, and manage AI algorithms for tenant subscription',
    'algo.upload': 'Upload Algorithm',
    'algo.stats.active': 'Active Algorithms',
    'algo.stats.pending': 'Pending Audit',
    'algo.stats.subs': 'Total Subscriptions',
    'algo.tab.all': 'All Algorithms',
    'algo.tab.audit': 'Audit Queue',
    'algo.col.name': 'Algorithm / Version',
    'algo.col.developer': 'Developer',
    'algo.col.category': 'Category',
    'algo.col.price': 'Price/Month',
    'algo.col.status': 'Status',
    'algo.col.date': 'Submitted',
    'algo.action.approve': 'Approve',
    'algo.action.reject': 'Reject',
    'algo.action.details': 'Details',
    'product.title': 'Product Center',
    'product.subtitle': 'Manage hardware, software, algorithms, and service packages',
    'product.add': 'Add Product',
    'product.addPackage': 'Create Package',
    'product.tab.products': 'Product List',
    'product.tab.packages': 'Package Management',
    'product.col.name': 'Product Name',
    'product.col.type': 'Type',
    'product.col.price': 'Price',
    'product.col.status': 'Status',
    'product.col.specs': 'Specs / Details',
    'product.col.pkgContent': 'Includes',
    'product.col.pkgSavings': 'Savings',
    'product.type.hardware': 'Hardware',
    'product.type.software': 'Software',
    'product.type.algorithm': 'Algorithm',
    'product.type.service': 'Service',
  },
  'zh-CN': {
    'app.title': '青泓云平台',
    'nav.dashboard': '运营看板',
    'nav.tenants': '租户管理',
    'nav.resources': '资源监控',
    'nav.billing': '计费中心',
    'nav.alerts': '告警中心',
    'nav.algorithms': '算法中心',
    'nav.products': '产品中心',
    'header.search': '搜索资源...',
    'header.role': '超级管理员',
    'dashboard.activeTenants': '活跃租户总数',
    'dashboard.newThisWeek': '本周新增 +2',
    'dashboard.criticalAlerts': '严重告警',
    'dashboard.immediateAttention': '需要立即处理',
    'dashboard.monthlyRevenue': '月度预估营收',
    'dashboard.basedOnUsage': '基于当前用量',
    'dashboard.systemHealth': '系统健康度',
    'dashboard.apiLatency': 'API 延迟: 45ms',
    'dashboard.globalApi': '全局 API 流量 (24h)',
    'dashboard.liveData': '实时数据',
    'dashboard.storageDist': '存储分布',
    'dashboard.totalUsed': '已用总量',
    'dashboard.alertsTitle': '严重告警与警告',
    'table.severity': '严重性',
    'table.message': '消息',
    'table.tenant': '租户',
    'table.time': '时间',
    'table.action': '操作',
    'action.investigate': '调查',
    'tenant.title': '租户管理',
    'tenant.subtitle': '管理服务生命周期与访问控制',
    'tenant.filter': '筛选',
    'tenant.new': '+ 新建租户',
    'tenant.search': '搜索名称、ID 或管理员...',
    'tenant.showing': '显示',
    'tenant.col.name': '租户名称 / ID',
    'tenant.col.status': '状态',
    'tenant.col.period': '服务期限',
    'tenant.col.usage': '资源使用情况',
    'tenant.col.balance': '余额',
    'tenant.col.actions': '操作',
    'tenant.loadMore': '加载更多',
    'billing.title': '计费中心',
    'billing.subtitle': '自动化账单生成与支付追踪',
    'billing.paymentSettings': '支付设置',
    'billing.runCycle': '执行计费周期',
    'billing.totalRevenue': '总营收 (本月)',
    'billing.vsLast': '环比 +12%',
    'billing.pendingInvoices': '待处理账单',
    'billing.needsAttention': '需关注',
    'billing.overdue': '逾期金额',
    'billing.frozen': '3 个账户已冻结',
    'billing.recent': '近期账单',
    'billing.col.id': '账单 ID',
    'billing.col.cycle': '计费周期',
    'billing.col.amount': '金额',
    'billing.col.status': '状态',
    'billing.col.date': '日期',
    'resource.title': '资源监控',
    'resource.subtitle': '实时用量统计与配额管理',
    'resource.cloudStorage': '云存储',
    'resource.sms': '短信发送',
    'resource.apiCalls': 'API 调用',
    'resource.algoTasks': '算法任务',
    'resource.totalUsage': '总用量',
    'resource.capacity': '容量',
    'resource.topConsumers': '资源消耗排名',
    'resource.channelConfig': '渠道配置',
    'resource.manageAll': '管理全部',
    'resource.active': '活跃',
    'ai.title': 'AI 智能助手',
    'ai.placeholder': '询问关于租户、告警或账单的问题...',
    'ai.thinking': '思考中...',
    'ai.welcome': '你好！我是您的运营助手。今天有什么可以帮您？',
    'algo.title': '算法中心',
    'algo.subtitle': '管理AI算法上架、审核与租户订阅',
    'algo.upload': '上传算法',
    'algo.stats.active': '已上架算法',
    'algo.stats.pending': '待审核',
    'algo.stats.subs': '总订阅数',
    'algo.tab.all': '所有算法',
    'algo.tab.audit': '审核队列',
    'algo.col.name': '算法名称 / 版本',
    'algo.col.developer': '开发者',
    'algo.col.category': '分类',
    'algo.col.price': '月订阅价',
    'algo.col.status': '状态',
    'algo.col.date': '提交时间',
    'algo.action.approve': '通过',
    'algo.action.reject': '驳回',
    'algo.action.details': '详情',
    'product.title': '产品中心',
    'product.subtitle': '管理硬件、软件、算法及服务套餐',
    'product.add': '新增产品',
    'product.addPackage': '创建套餐',
    'product.tab.products': '产品列表',
    'product.tab.packages': '套餐管理',
    'product.col.name': '产品名称',
    'product.col.type': '类型',
    'product.col.price': '价格',
    'product.col.status': '状态',
    'product.col.specs': '规格 / 描述',
    'product.col.pkgContent': '包含内容',
    'product.col.pkgSavings': '优惠',
    'product.type.hardware': '硬件',
    'product.type.software': '软件',
    'product.type.algorithm': '算法',
    'product.type.service': '服务',
  },
  'zh-TW': {
    'app.title': '青泓雲平台',
    'nav.dashboard': '營運儀表板',
    'nav.tenants': '租戶管理',
    'nav.resources': '資源監控',
    'nav.billing': '計費中心',
    'nav.alerts': '告警中心',
    'nav.algorithms': '演算法中心',
    'nav.products': '產品中心',
    'header.search': '搜尋資源...',
    'header.role': '超級管理員',
    'dashboard.activeTenants': '活躍租戶總數',
    'dashboard.newThisWeek': '本週新增 +2',
    'dashboard.criticalAlerts': '嚴重告警',
    'dashboard.immediateAttention': '需要立即處理',
    'dashboard.monthlyRevenue': '月度預估營收',
    'dashboard.basedOnUsage': '基於當前用量',
    'dashboard.systemHealth': '系統健康度',
    'dashboard.apiLatency': 'API 延遲: 45ms',
    'dashboard.globalApi': '全局 API 流量 (24h)',
    'dashboard.liveData': '即時數據',
    'dashboard.storageDist': '存儲分佈',
    'dashboard.totalUsed': '已用總量',
    'dashboard.alertsTitle': '嚴重告警與警告',
    'table.severity': '嚴重性',
    'table.message': '訊息',
    'table.tenant': '租戶',
    'table.time': '時間',
    'table.action': '操作',
    'action.investigate': '調查',
    'tenant.title': '租戶管理',
    'tenant.subtitle': '管理服務生命週期與存取控制',
    'tenant.filter': '篩選',
    'tenant.new': '+ 新建租戶',
    'tenant.search': '搜尋名稱、ID 或管理員...',
    'tenant.showing': '顯示',
    'tenant.col.name': '租戶名稱 / ID',
    'tenant.col.status': '狀態',
    'tenant.col.period': '服務期限',
    'tenant.col.usage': '資源使用情況',
    'tenant.col.balance': '餘額',
    'tenant.col.actions': '操作',
    'tenant.loadMore': '載入更多',
    'billing.title': '計費中心',
    'billing.subtitle': '自動化帳單生成與支付追蹤',
    'billing.paymentSettings': '支付設定',
    'billing.runCycle': '執行計費週期',
    'billing.totalRevenue': '總營收 (本月)',
    'billing.vsLast': '環比 +12%',
    'billing.pendingInvoices': '待處理帳單',
    'billing.needsAttention': '需關注',
    'billing.overdue': '逾期金額',
    'billing.frozen': '3 個帳戶已凍結',
    'billing.recent': '近期帳單',
    'billing.col.id': '帳單 ID',
    'billing.col.cycle': '計費週期',
    'billing.col.amount': '金額',
    'billing.col.status': '狀態',
    'billing.col.date': '日期',
    'resource.title': '資源監控',
    'resource.subtitle': '即時用量統計與配額管理',
    'resource.cloudStorage': '雲端存儲',
    'resource.sms': '簡訊發送',
    'resource.apiCalls': 'API 調用',
    'resource.algoTasks': '演算法任務',
    'resource.totalUsage': '總用量',
    'resource.capacity': '容量',
    'resource.topConsumers': '資源消耗排名',
    'resource.channelConfig': '渠道配置',
    'resource.manageAll': '管理全部',
    'resource.active': '活躍',
    'ai.title': 'AI 智能助手',
    'ai.placeholder': '詢問關於租戶、告警或帳單的問題...',
    'ai.thinking': '思考中...',
    'ai.welcome': '你好！我是您的運營助手。今天有什麼可以幫您？',
    'algo.title': '演算法中心',
    'algo.subtitle': '管理AI演算法上架、審核與租戶訂閱',
    'algo.upload': '上傳演算法',
    'algo.stats.active': '已上架演算法',
    'algo.stats.pending': '待審核',
    'algo.stats.subs': '總訂閱數',
    'algo.tab.all': '所有演算法',
    'algo.tab.audit': '審核隊列',
    'algo.col.name': '演算法名稱 / 版本',
    'algo.col.developer': '開發者',
    'algo.col.category': '分類',
    'algo.col.price': '月訂閱價',
    'algo.col.status': '狀態',
    'algo.col.date': '提交時間',
    'algo.action.approve': '通過',
    'algo.action.reject': '駁回',
    'algo.action.details': '詳情',
    'product.title': '產品中心',
    'product.subtitle': '管理硬體、軟體、演算法及服務套餐',
    'product.add': '新增產品',
    'product.addPackage': '創建套餐',
    'product.tab.products': '產品列表',
    'product.tab.packages': '套餐管理',
    'product.col.name': '產品名稱',
    'product.col.type': '類型',
    'product.col.price': '價格',
    'product.col.status': '狀態',
    'product.col.specs': '規格 / 描述',
    'product.col.pkgContent': '包含內容',
    'product.col.pkgSavings': '優惠',
    'product.type.hardware': '硬體',
    'product.type.software': '軟體',
    'product.type.algorithm': '演算法',
    'product.type.service': '服務',
  },
  si: {
    'app.title': 'Qingyun Cloud',
    'nav.dashboard': 'මෙහෙයුම් පුවරුව',
    'nav.tenants': 'පරිශීලක කළමනාකරණය',
    'nav.resources': 'සම්පත් නිරීක්ෂක',
    'nav.billing': 'බිල්පත් මධ්යස්ථානය',
    'nav.alerts': 'ඇඟවීම් මධ්යස්ථානය',
    'nav.algorithms': 'ඇල්ගොරිතම මධ්‍යස්ථානය',
    'nav.products': 'නිෂ්පාදන මධ්‍යස්ථානය',
    'header.search': 'සම්පත් සොයන්න...',
    'header.role': 'ප්‍රධාන පරිපාලක',
    'dashboard.activeTenants': 'සක්‍රිය පරිශීලකයින්',
    'dashboard.newThisWeek': 'මෙම සතියේ +2',
    'dashboard.criticalAlerts': 'බරපතල ඇඟවීම්',
    'dashboard.immediateAttention': 'වහාම අවධානය අවශ්යයි',
    'dashboard.monthlyRevenue': 'මාසික ආදායම',
    'dashboard.basedOnUsage': 'වත්මන් භාවිතය මත',
    'dashboard.systemHealth': 'පද්ධති සෞඛ්යය',
    'dashboard.apiLatency': 'API ප්‍රමාදය: 45ms',
    'dashboard.globalApi': 'API ගමනාගමනය (24h)',
    'dashboard.liveData': 'සජීවී දත්ත',
    'dashboard.storageDist': 'ගබඩා බෙදා හැරීම',
    'dashboard.totalUsed': 'මුළු භාවිතය',
    'dashboard.alertsTitle': 'බරපතල ඇඟවීම්',
    'table.severity': 'බරපතලකම',
    'table.message': 'පණිවිඩය',
    'table.tenant': 'පරිශීලක',
    'table.time': 'වේලාව',
    'table.action': 'ක්‍රියාව',
    'action.investigate': 'විමර්ශනය',
    'tenant.title': 'පරිශීලක කළමනාකරණය',
    'tenant.subtitle': 'සේවා සහ ප්‍රවේශ පාලනය',
    'tenant.filter': 'පෙරහන්',
    'tenant.new': '+ නව පරිශීලක',
    'tenant.search': 'නම හෝ ID මගින් සොයන්න...',
    'tenant.showing': 'පෙන්වමින්',
    'tenant.col.name': 'නම / ID',
    'tenant.col.status': 'තත්වය',
    'tenant.col.period': 'සේවා කාලය',
    'tenant.col.usage': 'සම්පත් භාවිතය',
    'tenant.col.balance': 'ශේෂය',
    'tenant.col.actions': 'ක්‍රියා',
    'tenant.loadMore': 'තව පූරණය කරන්න',
    'billing.title': 'බිල්පත් මධ්යස්ථානය',
    'billing.subtitle': 'ස්වයංක්‍රීය බිල්පත් උත්පාදනය',
    'billing.paymentSettings': 'ගෙවීම් සැකසුම්',
    'billing.runCycle': 'බිල්පත් චක්‍රය',
    'billing.totalRevenue': 'මුළු ආදායම',
    'billing.vsLast': 'පසුගිය මාසයට සාපේක්ෂව +12%',
    'billing.pendingInvoices': 'පොරොත්තු බිල්පත්',
    'billing.needsAttention': 'අවධානය අවශ්යයි',
    'billing.overdue': 'ප්‍රමාද වූ මුදල',
    'billing.frozen': 'ගිණුම් 3 ක් අත්හිටුවා ඇත',
    'billing.recent': 'මෑත බිල්පත්',
    'billing.col.id': 'බිල්පත් ID',
    'billing.col.cycle': 'චක්‍රය',
    'billing.col.amount': 'මුදල',
    'billing.col.status': 'තත්වය',
    'billing.col.date': 'දිනය',
    'resource.title': 'සම්පත් නිරීක්ෂක',
    'resource.subtitle': 'තථ්ය කාලීන භාවිත දත්ත',
    'resource.cloudStorage': 'වලාකුළු ගබඩාව',
    'resource.sms': 'SMS යැවූ',
    'resource.apiCalls': 'API ඇමතුම්',
    'resource.algoTasks': 'ඇල්ගොරිතම කාර්යයන්',
    'resource.totalUsage': 'මුළු භාවිතය',
    'resource.capacity': 'ධාරිතාව',
    'resource.topConsumers': 'ඉහළම පාරිභෝගිකයින්',
    'resource.channelConfig': 'නාලිකා සැකසුම',
    'resource.manageAll': 'සියල්ල කළමනාකරණය',
    'resource.active': 'සක්‍රිය',
    'ai.title': 'AI සහායක',
    'ai.placeholder': 'ඕනෑම දෙයක් අසන්න...',
    'ai.thinking': 'සිතමින්...',
    'ai.welcome': 'ආයුබෝවන්! මම ඔබේ මෙහෙයුම් සහායකයා. මම ඔබට උදව් කරන්නේ කෙසේද?',
    'algo.title': 'ඇල්ගොරිතම මධ්‍යස්ථානය',
    'algo.subtitle': 'ඇල්ගොරිතම සහ දායකත්වයන් කළමනාකරණය',
    'algo.upload': 'උඩුගත කරන්න',
    'algo.stats.active': 'සක්‍රිය ඇල්ගොරිතම',
    'algo.stats.pending': 'පොරොත්තු විගණන',
    'algo.stats.subs': 'මුළු දායකත්වයන්',
    'algo.tab.all': 'සියලුම ඇල්ගොරිතම',
    'algo.tab.audit': 'විගණන පෝලිම',
    'algo.col.name': 'නම / අනුවාදය',
    'algo.col.developer': 'සංවර්ධක',
    'algo.col.category': 'වර්ගය',
    'algo.col.price': 'මිල',
    'algo.col.status': 'තත්වය',
    'algo.col.date': 'දිනය',
    'algo.action.approve': 'අනුමත කරන්න',
    'algo.action.reject': 'ප්‍රතික්ෂේප කරන්න',
    'algo.action.details': 'විස්තර',
    'product.title': 'නිෂ්පාදන මධ්‍යස්ථානය',
    'product.subtitle': 'දෘඩාංග, මෘදුකාංග, ඇල්ගොරිතම සහ සේවා කළමනාකරණය',
    'product.add': 'නිෂ්පාදන එකතු කරන්න',
    'product.addPackage': 'පැකේජ සාදන්න',
    'product.tab.products': 'නිෂ්පාදන ලැයිස්තුව',
    'product.tab.packages': 'පැකේජ කළමනාකරණය',
    'product.col.name': 'නම',
    'product.col.type': 'වර්ගය',
    'product.col.price': 'මිල',
    'product.col.status': 'තත්වය',
    'product.col.specs': 'පිරිවිතර',
    'product.col.pkgContent': 'අන්තර්ගතය',
    'product.col.pkgSavings': 'ඉතිරිකිරීම්',
    'product.type.hardware': 'දෘඩාංග',
    'product.type.software': 'මෘදුකාංග',
    'product.type.algorithm': 'ඇල්ගොරිතම',
    'product.type.service': 'සේවා',
  },
  ta: {
    'app.title': 'Qingyun Cloud',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.tenants': 'குத்தகைதாரர்',
    'nav.resources': 'வள கண்காணிப்பு',
    'nav.billing': 'பில்லிங் மையம்',
    'nav.alerts': 'எச்சரிக்கை மையம்',
    'nav.algorithms': 'அல்காரிதம் மையம்',
    'nav.products': 'தயாரிப்பு மையம்',
    'header.search': 'தேடல்...',
    'header.role': 'நிர்வாகி',
    'dashboard.activeTenants': 'செயலில் உள்ள குத்தகைதாரர்கள்',
    'dashboard.newThisWeek': 'இந்த வாரம் +2',
    'dashboard.criticalAlerts': 'முக்கிய எச்சரிக்கைகள்',
    'dashboard.immediateAttention': 'உடனடி கவனம் தேவை',
    'dashboard.monthlyRevenue': 'மாதாந்திர வருவாய்',
    'dashboard.basedOnUsage': 'தற்போதைய பயன்பாட்டின் அடிப்படையில்',
    'dashboard.systemHealth': 'அமைப்பு ஆரோக்கியம்',
    'dashboard.apiLatency': 'API தாமதம்: 45ms',
    'dashboard.globalApi': 'API போக்குவரத்து (24h)',
    'dashboard.liveData': 'நேரலை',
    'dashboard.storageDist': 'சேமிப்பு விநியோகம்',
    'dashboard.totalUsed': 'மொத்தம் பயன்படுத்தப்பட்டது',
    'dashboard.alertsTitle': 'முக்கிய எச்சரிக்கைகள்',
    'table.severity': 'தீவிரம்',
    'table.message': 'செய்தி',
    'table.tenant': 'குத்தகைதாரர்',
    'table.time': 'நேரம்',
    'table.action': 'செயல்',
    'action.investigate': 'விசாரி',
    'tenant.title': 'குத்தகைதாரர் மேலாண்மை',
    'tenant.subtitle': 'சேவை மற்றும் அணுகல் கட்டுப்பாடு',
    'tenant.filter': 'வடிகட்டி',
    'tenant.new': '+ புதிய குத்தகைதாரர்',
    'tenant.search': 'பெயர் அல்லது ID மூலம் தேடு...',
    'tenant.showing': 'காட்டுகிறது',
    'tenant.col.name': 'பெயர் / ID',
    'tenant.col.status': 'நிலை',
    'tenant.col.period': 'சேவை காலம்',
    'tenant.col.usage': 'வள பயன்பாடு',
    'tenant.col.balance': 'மீதி',
    'tenant.col.actions': 'செயல்கள்',
    'tenant.loadMore': 'மேலும் ஏற்றவும்',
    'billing.title': 'பில்லிங் மையம்',
    'billing.subtitle': 'தானியங்கி விலைப்பட்டியல்',
    'billing.paymentSettings': 'கட்டண அமைப்புகள்',
    'billing.runCycle': 'பில்லிங் சுழற்சி',
    'billing.totalRevenue': 'மொத்த வருவாய்',
    'billing.vsLast': 'கடந்த மாதத்தை விட +12%',
    'billing.pendingInvoices': 'நிலுவையில் உள்ள விலைப்பட்டியல்',
    'billing.needsAttention': 'கவனம் தேவை',
    'billing.overdue': 'தாமதமான தொகை',
    'billing.frozen': '3 கணக்குகள் முடக்கப்பட்டுள்ளன',
    'billing.recent': 'சமீபத்திய விலைப்பட்டியல்',
    'billing.col.id': 'விலைப்பட்டியல் ID',
    'billing.col.cycle': 'சுழற்சி',
    'billing.col.amount': 'தொகை',
    'billing.col.status': 'நிலை',
    'billing.col.date': 'தேதி',
    'resource.title': 'வள கண்காணிப்பு',
    'resource.subtitle': 'நிகழ்நேர புள்ளிவிவரங்கள்',
    'resource.cloudStorage': 'மேகக்கணி சேமிப்பு',
    'resource.sms': 'SMS அனுப்பப்பட்டது',
    'resource.apiCalls': 'API அழைப்புகள்',
    'resource.algoTasks': 'அல்காரிதம் பணிகள்',
    'resource.totalUsage': 'மொத்த பயன்பாடு',
    'resource.capacity': 'கொள்ளளவு',
    'resource.topConsumers': 'அதிக நுகர்வோர்',
    'resource.channelConfig': 'சேனல் கட்டமைப்பு',
    'resource.manageAll': 'நிர்வகி',
    'resource.active': 'செயலில்',
    'ai.title': 'AI உதவியாளர்',
    'ai.placeholder': 'ஏதேனும் கேட்கவும்...',
    'ai.thinking': 'சி சிந்திக்கிறது...',
    'ai.welcome': 'வணக்கம்! நான் உங்கள் செயல்பாட்டு உதவியாளர். நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    'algo.title': 'அல்காரிதம் மையம்',
    'algo.subtitle': 'அல்காரிதம் மேலாண்மை மற்றும் சந்தாக்கள்',
    'algo.upload': 'பதிவேற்றம்',
    'algo.stats.active': 'செயலில் உள்ள அல்காரிதம்கள்',
    'algo.stats.pending': 'நிலுவையில் உள்ள தணிக்கை',
    'algo.stats.subs': 'மொத்த சந்தாக்கள்',
    'algo.tab.all': 'அனைத்து அல்காரிதம்கள்',
    'algo.tab.audit': 'தணிக்கை வரிசை',
    'algo.col.name': 'பெயர் / பதிப்பு',
    'algo.col.developer': 'டெவலப்பர்',
    'algo.col.category': 'வகை',
    'algo.col.price': 'விலை',
    'algo.col.status': 'நிலை',
    'algo.col.date': 'தேதி',
    'algo.action.approve': 'ஏற்றுக்கொள்',
    'algo.action.reject': 'நிராகரி',
    'algo.action.details': 'விவரங்கள்',
    'product.title': 'தயாரிப்பு மையம்',
    'product.subtitle': 'வன்பொருள், மென்பொருள், அல்காரிதம் மற்றும் சேவைகளை நிர்வகிக்கவும்',
    'product.add': 'சேர்',
    'product.addPackage': 'தொகுப்பை உருவாக்கவும்',
    'product.tab.products': 'தயாரிப்பு பட்டியல்',
    'product.tab.packages': 'தொகுப்பு மேலாண்மை',
    'product.col.name': 'பெயர்',
    'product.col.type': 'வகை',
    'product.col.price': 'விலை',
    'product.col.status': 'நிலை',
    'product.col.specs': 'விவரக்குறிப்புகள்',
    'product.col.pkgContent': 'உள்ளடக்கம்',
    'product.col.pkgSavings': 'சேமிப்பு',
    'product.type.hardware': 'வன்பொருள்',
    'product.type.software': 'மென்பொருள்',
    'product.type.algorithm': 'அல்காரிதம்',
    'product.type.service': 'சேவை',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh-CN');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};

// --- Theme System ---

interface ThemeContextType {
  theme: Theme;
  toggleTheme: () => void;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const ThemeProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [theme, setTheme] = useState<Theme>('light');

  useEffect(() => {
    const root = window.document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => (prev === 'light' ? 'dark' : 'light'));
  };

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};
